## ACSのTract_Community別データをコミュニティ別に計数する

#### 整理工程一貫ファイルのcsvを使用

In [19]:
import pandas as pd
import numpy as np

In [39]:
dataset = "B17001"
name = ""
df1 = pd.read_csv(rf"E:\USB_DISK\JupyterLab Cleaned File\TractレベルACS\完成版\変数ピックアップ済み\{name}ACS_Tract_weighted_{dataset}_2010-2024.csv")

### 整理したデータを結合する先のcsvファイル読み込み

In [40]:
header = pd.read_csv(r"E:\USB_DISK\JupyterLab Cleaned File\CommunityレベルACS\ACS_Community.csv")

In [41]:
# header["comm_pop"] = header["comm_pop"].astype(int)

In [42]:
header.head()

,year,community_area,comm_pop,community,commarea_km2,malepop,male15_19pop,male15_24pop,male15_29pop,allwhitepop,...,pov_pop,pov_male_pop,pov_male_u15_pop,pov_male_15to17_pop,pov_male_18to24_pop,pov_male_25to44_pop,pov_fem_u15_pop,pov_fem_15to17_pop,pov_fem_18to24_pop,pov_fem_25to44_pop
0,2010,1,55006,ROGERS PARK,51.259902,27043,1437,3831,6674,28845,...,13687,6210,1618,286,1225,1881,1640,479,1463,2200
1,2010,2,72069,WEST RIDGE,98.429095,34222,2008,4598,6994,38876,...,12495,5939,2404,325,741,1373,1876,413,752,1785
2,2010,3,56340,UPTOWN,65.095643,30643,1017,3087,7679,32831,...,14256,7316,1259,124,794,2232,1091,145,1186,1933
3,2010,4,38417,LINCOLN SQUARE,71.352328,18887,1022,1949,4416,27317,...,4392,1971,481,157,290,594,463,122,321,881
4,2010,5,33394,NORTH CENTER,57.054168,16486,503,1525,3939,29139,...,2416,956,89,94,140,279,218,0,458,212

In [43]:
df1.columns

Index(['year', 'pov_rate', 'pov_male_rate', 'pov_male_u15_rate',
       'pov_male_15to17_rate', 'pov_male_18to24_rate', 'pov_male_25to44_rate',
       'pov_fem_rate', 'pov_fem_u15_rate', 'pov_fem_15to17_rate',
       'pov_fem_18to24_rate', 'pov_fem_25to44_rate', 'geoid', 'namelsad',
       'tractpop', 'tractce', 'community_area', 'weight', 'comm_pop',
       'pop_share', 'community', 'commarea_km2'],
      dtype='str')

In [44]:
df1["geoid"].dtype

dtype('int64')

In [45]:
# header["community_area"].dtype

In [46]:
df1.head(6)

,year,pov_rate,pov_male_rate,pov_male_u15_rate,pov_male_15to17_rate,pov_male_18to24_rate,pov_male_25to44_rate,pov_fem_rate,pov_fem_u15_rate,pov_fem_15to17_rate,...,geoid,namelsad,tractpop,tractce,community_area,weight,comm_pop,pop_share,community,commarea_km2
0,2010,0.03035,0.03314,0.06204,0.04768,0.02717,0.02712,0.02767,0.05126,0.00000,...,17031842400,Census Tract 8424,3766,842400,44,1.0,35023,0.107529,CHATHAM,82.320670
1,2010,0.05290,0.05533,0.10486,0.00000,0.03463,0.06184,0.05083,0.05174,0.10112,...,17031840300,Census Tract 8403,4085,840300,59,1.0,15626,0.261423,MCKINLEY PARK,39.431800
2,2010,0.15241,0.14389,0.12848,0.24032,0.15854,0.17717,0.15960,0.14923,0.10004,...,17031841100,Census Tract 8411,6970,841100,34,1.0,13595,0.512688,ARMOUR SQUARE,27.766196
3,2010,0.04410,0.03707,0.03676,0.07357,0.03298,0.03095,0.05222,0.07244,0.07113,...,17031841200,Census Tract 8412,4946,841200,31,1.0,35508,0.139293,LOWER WEST SIDE,81.550724
4,2010,0.03824,0.01947,0.00000,NaN,0.16088,0.01237,0.05216,0.01767,0.00000,...,17031839000,Census Tract 8390,5499,839000,32,1.0,19993,0.275046,LOOP,46.335565
5,2010,0.00672,0.00862,0.00690,0.00000,0.02052,0.00665,0.00420,0.01035,0.00000,...,17031838200,Census Tract 8382,1495,838200,28,1.0,49788,0.030027,NEAR WEST SIDE,158.492467

### Communityarea x year　ごとに集計し，新しい表を作る

In [47]:
# 集計対象列（後ろ10列を除く）
sum_cols = df1.columns[:-10]

# year, community_area はグループキーとして残すので除外
sum_cols = [col for col in sum_cols if col not in ["year", "community_area"]]

# 集計
result = (
    df1.groupby(["year", "community_area"], as_index=False)[sum_cols]
      .sum()
)

print(result.head())

   year  community_area  pov_rate  pov_male_rate  pov_male_u15_rate  \
0  2010               1   0.25713        0.23658            0.32639
1  2010               2   0.17478        0.17383            0.30681
2  2010               3   0.26051        0.23863            0.32668
3  2010               4   0.11503        0.10552            0.14210
4  2010               5   0.07254        0.05770            0.03125

   pov_male_15to17_rate  pov_male_18to24_rate  pov_male_25to44_rate  \
0               0.39838               0.39349               0.17364
1               0.22633               0.19579               0.13570
2               0.15566               0.28589               0.16002
3               0.16615               0.22326               0.07325
4               0.12554               0.11726               0.03422

   pov_fem_rate  pov_fem_u15_rate  pov_fem_15to17_rate  pov_fem_18to24_rate  \
0       0.27401           0.34677              0.38104              0.33960
1       0.17256           0.21106              0.22948              0.21161
2       0.28731           0.38561              0.39046              0.41402
3       0.12456           0.17045              0.20228              0.16036
4       0.08740           0.07629              0.00000              0.43826

   pov_fem_25to44_rate
0              0.22648
1              0.18074
2              0.19000
3              0.10319
4              0.02711

In [48]:
# result["male15_29pop"].isna().sum()

In [49]:
result.head()

,year,community_area,pov_rate,pov_male_rate,pov_male_u15_rate,pov_male_15to17_rate,pov_male_18to24_rate,pov_male_25to44_rate,pov_fem_rate,pov_fem_u15_rate,pov_fem_15to17_rate,pov_fem_18to24_rate,pov_fem_25to44_rate
0,2010,1,0.25713,0.23658,0.32639,0.39838,0.39349,0.17364,0.27401,0.34677,0.38104,0.33960,0.22648
1,2010,2,0.17478,0.17383,0.30681,0.22633,0.19579,0.13570,0.17256,0.21106,0.22948,0.21161,0.18074
2,2010,3,0.26051,0.23863,0.32668,0.15566,0.28589,0.16002,0.28731,0.38561,0.39046,0.41402,0.19000
3,2010,4,0.11503,0.10552,0.14210,0.16615,0.22326,0.07325,0.12456,0.17045,0.20228,0.16036,0.10319
4,2010,5,0.07254,0.05770,0.03125,0.12554,0.11726,0.03422,0.08740,0.07629,0.00000,0.43826,0.02711

### csvに保存

In [50]:
result.to_csv(rf"E:\USB_DISK\JupyterLab Cleaned File\CommunityレベルACS\完成品\{name}ACS_Community_{dataset}.csv", index = False)

In [51]:
result.columns

Index(['year', 'community_area', 'pov_rate', 'pov_male_rate',
       'pov_male_u15_rate', 'pov_male_15to17_rate', 'pov_male_18to24_rate',
       'pov_male_25to44_rate', 'pov_fem_rate', 'pov_fem_u15_rate',
       'pov_fem_15to17_rate', 'pov_fem_18to24_rate', 'pov_fem_25to44_rate'],
      dtype='str')

### ヘッダーに結合する

In [52]:
result2 = header.merge(
    result,
    on=["year", "community_area"],
    how="left"
)

In [53]:
len(result2)

1155

In [54]:
result2

,year,community_area,comm_pop,community,commarea_km2,malepop,male15_19pop,male15_24pop,male15_29pop,allwhitepop,...,pov_male_rate,pov_male_u15_rate,pov_male_15to17_rate,pov_male_18to24_rate,pov_male_25to44_rate,pov_fem_rate,pov_fem_u15_rate,pov_fem_15to17_rate,pov_fem_18to24_rate,pov_fem_25to44_rate
0,2010,1,55006,ROGERS PARK,51.259902,27043,1437,3831,6674,28845,...,0.23658,0.32639,0.39838,0.39349,0.17364,0.27401,0.34677,0.38104,0.33960,0.22648
1,2010,2,72069,WEST RIDGE,98.429095,34222,2008,4598,6994,38876,...,0.17383,0.30681,0.22633,0.19579,0.13570,0.17256,0.21106,0.22948,0.21161,0.18074
2,2010,3,56340,UPTOWN,65.095643,30643,1017,3087,7679,32831,...,0.23863,0.32668,0.15566,0.28589,0.16002,0.28731,0.38561,0.39046,0.41402,0.19000
3,2010,4,38417,LINCOLN SQUARE,71.352328,18887,1022,1949,4416,27317,...,0.10552,0.14210,0.16615,0.22326,0.07325,0.12456,0.17045,0.20228,0.16036,0.10319
4,2010,5,33394,NORTH CENTER,57.054168,16486,503,1525,3939,29139,...,0.05770,0.03125,0.12554,0.11726,0.03422,0.08740,0.07629,0.00000,0.43826,0.02711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150,2024,73,24851,WASHINGTON HEIGHTS,79.635753,10591,702,1286,2173,1400,...,0.18900,0.23683,0.30974,0.21778,0.15056,0.14590,0.21177,0.10820,0.06746,0.17627
1151,2024,74,19059,MOUNT GREENWOOD,75.584290,9243,512,1119,1376,17870,...,0.03457,0.00539,0.09440,0.14206,0.00670,0.07064,0.05538,0.08848,0.10249,0.04799
1152,2024,75,20865,MORGAN PARK,91.877341,9479,450,1082,1429,6971,...,0.14358,0.25878,0.22420,0.16955,0.09678,0.20864,0.24679,0.23607,0.27717,0.20039
1153,2024,76,14145,OHARE,371.835608,7500,449,763,1376,10280,...,0.07467,0.17895,0.16119,0.07486,0.04164,0.10135,0.14426,0.07676,0.14390,0.09055
1154,2024,77,56563,EDGEWATER,48.449991,28516,1209,3117,5755,37734,...,0.14071,0.23278,0.23802,0.22047,0.10689,0.18800,0.15977,0.14309,0.43204,0.11483

In [55]:
list(result2.columns)
len(list(result2.columns))

148

In [56]:
list(result2.isna().sum())

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

### 結合後のデータセットを保存

In [57]:
result2.to_csv(r"E:\USB_DISK\JupyterLab Cleaned File\CommunityレベルACS\ACS_Community.csv", index = False)